"""Create table users and user_files

Revision ID: 7d3e619c9755
Revises: 
Create Date: 2024-05-05 01:37:20.310850

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d3e619c9755"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("user_name", sa.String(), nullable=False),
    sa.Column("password", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table("user_files",
    sa.Column("file_id", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("file_hash", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.user_id"] ),
    sa.PrimaryKeyConstraint("file_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_files")
    op.drop_table("users")
    # ### end Alembic commands ###
